# Project Information
site_name: Cuit-Wiki
site_author: CUIT ACM
site_url: https://cuit-wiki.crotes.top/
strict: false

# Repository
repo_name: 'Crotes/Cuit-Wiki'
repo_url: 'https://github.com/Crotes/Cuit-Wiki'
edit_uri: 'https://github.com/Crotes/Cuit-Wiki/edit/main/docs/'

# Copyright
copyright: 'Copyright &copy; 2022 - 2022 Cuit Wiki'

# Contents
nav:
  - '简介': 'index.md'
  - '基础': 
    - 'Base/index.md'
    - '语法基础': 
      - '函数': 'Base/函数.md'
      - '指针': 'Base/指针.md'
      - '引用': 'Base/引用.md'
      - '结构体': 'Base/结构体.md'
      - '重载': 'Base/重载.md'
    - '算法基础':
      - '递归回溯': 'Base/递归回溯.md'
      - '递推': 'Base/递推.md'
      - '贪心': 'Base/贪心.md'
      - '二分': 'Base/二分.md'
      - '排序':
        - '选择排序': 'Base/选择排序.md'
        - '冒泡排序': 'Base/冒泡排序.md'
        - '插入排序': 'Base/插入排序.md'
        - '快速排序': 'Base/快速排序.md'
        - '归并排序': 'Base/归并排序.md'
        - '桶排序': 'Base/桶排序.md'
        - '计数排序': 'Base/计数排序.md' 
      - '高精度': 'Base/高精度.md'
      - '位运算': 'Base/位运算.md'
      - '时空复杂度分析': 'Base/时空复杂度分析.md'
  - '数据结构': 
    - 'Datastructure/index.md'
    - '队列': 'Datastructure/队列.md'
    - '栈': 'Datastructure/栈.md'
    - '链表': 'Datastructure/链表.md'
    - '堆': 'Datastructure/堆.md'
    - '树':
      - '树的基础': 'Datastructure/树的基础.md'
      - '线段树': 'Datastructure/线段树.md'
      - '树状数组': 'Datastructure/树状数组.md'
      - '平衡树': 'Datastructure/平衡树.md'
      - '树套树': 'Datastructure/树套树.md'
      - '树链剖分': 'Datastructure/树链剖分.md'
      - '笛卡尔树': 'Datastructure/笛卡尔树.md'
      - '树的启发式合并': 'Datastructure/树的启发式合并.md'
      - 'DSU on tree': 'Datastructure/DSU.md'
      - 'LCT': 'Datastructure/LCT.md'
      - '虚树': 'Datastructure/虚树.md'
      - 'KD树': 'Datastructure/KD树.md'
      - '树的哈希': 'Datastructure/树的哈希.md'
      - '析合树': 'Datastructure/析合树.md'
    - '并查集': 'Datastructure/并查集.md'
    - '分块': 'Datastructure/分块.md'
    - 'STL': 
      - 'pair': 'Datastructure/pair.md' 
      - 'vector': 'Datastructure/vector.md'
      - 'priority_queue': 'Datastructure/priority_queue.md'
      - 'set': 'Datastructure/set.md'
      - 'map': 'Datastructure/map.md'
      - 'multiset': 'Datastructure/multiset.md'
      - 'bitset': 'Datastructure/bitset.md'
      - 'pbds': 'Datastructure/pbds.md'
    - 'ST表': 'Datastructure/RMQ.md'
  - '图论': 
    - 'Graph/index.md'
    - '图的概念': 'Graph/图的概念.md'
    - '图的遍历': 'Graph/图的遍历.md'
    - '拓扑序': 'Graph/拓扑序.md'
    - '传递闭包': 'Graph/传递闭包.md'
    - '最短路': 'Graph/最短路.md'
    - '最小生成树': 'Graph/最小生成树.md'
    - '点(边)双连通分量': 'Graph/点(边)双连通分量.md'
    - '最近公共祖先': 'Graph/lca.md'
    - '二分图':
      - '二分图判定': 'Graph/二分图判定.md'
      - '匈牙利算法': 'Graph/匈牙利算法.md'
      - 'KM': 'Graph/KM.md'
      - 'hopcraft-karp': 'Graph/hopcraft-karp.md'
    - '网络流':
      - '最大流': 'Graph/最大流.md'
      - '费用流': 'Graph/费用流.md'
      - '上下界网络流': 'Graph/上下界网络流.md'
    - '欧拉路': 'Graph/欧拉路.md'
    - '2-sat': 'Graph/2-sat.md'
    - '竞赛图': 'Graph/竞赛图.md'
    - '差分约束': 'Graph/差分约束.md'
    - '斯坦纳树': 'Graph/斯坦纳树.md'
    - '仙人掌': 'Graph/仙人掌.md'
    - '最小树形图': 'Graph/最小树形图.md'
    - '一般图匹配': 'Graph/一般图匹配.md'
    - 'K短路': 'Graph/K短路.md'
    - '支配树': 'Graph/支配树.md'
    - '全局最小割': 'Graph/全局最小割.md'
  - '动态规划': 
    - 'Dp/index.md'
    - '线性dp及01背包入门': 'Dp/线性dp及01背包入门.md'
    - '背包问题': 'Dp/背包问题.md'
    - '区间dp': 'Dp/区间dp.md'
    - '数位dp': 'Dp/数位dp.md'
    - '树形dp': 'Dp/树形dp.md'
    - '状压dp': 'Dp/状压dp.md'
    - '概率dp': 'Dp/概率dp.md'
    - '计数dp': 'Dp/计数dp.md'
    - '其他dp': 'Dp/其他dp.md'
    - 'dp优化': 'Dp/dp优化.md'
  - '字符串': 
    - 'String/index.md'
    - 'kmp': 'String/kmp.md'
    - '字符串的hash': 'String/字符串的hash.md'
    - '字典树': 'String/字典树.md'
    - 'AC自动机': 'String/AC自动机.md'
    - '后缀数组': 'String/后缀数组.md'
    - '后缀自动机': 'String/后缀自动机.md'
    - '回文自动机': 'String/回文自动机.md'
    - '扩展kmp': 'String/扩展kmp.md'
    - 'manacher': 'String/manacher.md'
    - '最小表示法': 'String/最小表示法.md'
    - 'Lyndon分解': 'String/Lyndon分解.md'
  - '数学': 
    - 'Math/index.md'
    - '数论':
      - '埃氏筛': 'Math/埃氏筛.md'
      - 'gcd/lcm': 'Math/gcd.md'
      - '快速幂': 'Math/快速幂.md'
      - '逆元': 'Math/逆元.md'  
      - '扩展欧几里得': 'Math/扩展欧几里得.md'
      - '费马定理/欧拉定理': 'Math/费马定理.md' 
      - '扩展欧拉定理': 'Math/扩展欧拉定理.md'
      - '原根': 'Math/原根.md'
      - '类欧几里得': 'Math/类欧几里得.md'
      - '同余方程组': 'Math/同余方程组.md'
      - 'Lucas': 'Math/Lucas.md'
      - '离散对数': 'Math/离散对数.md' 
      - '数论函数': 
        - '线性筛': 'Math/线性筛.md'
        - '整除分块': 'Math/整除分块.md'
        - '迪利克雷卷积': 'Math/迪利克雷卷积.md'
        - '莫比乌斯函数': 'Math/莫比乌斯函数.md'
        - '杜教筛': 'Math/杜教筛.md' 
        - 'min25筛': 'Math/min25筛.md'
      - 'Miller Rabin': 'Math/Miller Rabin.md'
      - 'Pollard Rho': 'Math/Pollard Rho.md'
    - '线性代数':
      - '矩阵快速幂': 'Linear Algebra/矩阵快速幂.md'
      - '高斯消元': 'Linear Algebra/高斯消元.md'
      - '行列式': 'Linear Algebra/行列式.md'
      - '线性基': 'Linear Algebra/线性基.md'
      - '矩阵求逆': 'Linear Algebra/矩阵求逆.md'
      - '常系数线性递推': 'Linear Algebra/常系数线性递推.md' 
      - '矩阵树定理': 'Linear Algebra/矩阵树定理.md'
      - 'BM': 'Linear Algebra/BM.md'
    - '组合数学':
      - '组合数': 'Combinatorics/组合数.md'
      - '球盒问题': 'Combinatorics/球盒问题.md'
      - '二项式定理': 'Combinatorics/二项式定理.md'
      - '概率论': 'Combinatorics/概率论.md'
      - '容斥定理':
        - '基础': 'Combinatorics/容斥定理基础.md'
        - 'min-max容斥': 'Combinatorics/min-max容斥.md'
        - '二项式反演': 'Combinatorics/二项式反演.md'
      - '常见数列':
        - '斐波拉契数列': 'Combinatorics/斐波拉契数列.md'
        - '错排问题': 'Combinatorics/错排问题.md'
        - '卡特兰数': 'Combinatorics/卡特兰数.md'
        - '拆分数': 'Combinatorics/拆分数.md'
        - '斯特林数': 'Combinatorics/斯特林数.md'
        - '贝尔数': 'Combinatorics/贝尔数.md' 
        - '伯努利数': 'Combinatorics/伯努利数.md'
      - 'purfer序列': 'Combinatorics/purfer序列.md'
    - '博弈论':
      - 'SG函数': 'Game/SG函数.md'
      - '常见结论': 'Game/常见结论.md'
    - '多项式':
      - 'FFT/NTT': 'Polynomial/FFT.md'
      - '拉格朗日插值': 'Polynomial/拉格朗日插值.md'
      - '生成函数': 'Polynomial/生成函数.md'
      - '多项式全家桶': 'Polynomial/多项式全家桶.md'
      - '集合幂级数': 'Polynomial/集合幂级数.md'
    - '群论': 
      - '置换': 'Group/置换.md'
      - 'Burnside引理': 'Group/Burnside引理.md'
      - 'Polya定理': 'Group/Polya定理.md'
    - '线性规划': 'Linear Programming/线性规划.md'
  - '几何': 
    - 'Geometry/index.md'
    - '点类': 
      - '点积': 'Geometry/点积.md'
      - '叉积': 'Geometry/叉积.md'
      - '极角序': 'Geometry/极角序.md'
    - '线段相关':
      - '相交判定': 'Geometry/相关判定.md'
      - '交点': 'Geometry/交点.md'
    - '多边形相关':
      - '凸包': 'Geometry/凸包.md'
      - '多边形包含': 'Geometry/多边形包含.md'
      - '旋转卡壳': 'Geometry/旋转卡壳.md'
      - '半平面相交': 'Geometry/半平面相交.md'
    - '圆相关':
      - '交点切线': 'Geometry/交点切线.md'
      - '面积交/并': 'Geometry/面积交.md'
    - '凸包快速操作': 'Geometry/凸包快速操作.md'
    - '三维计算几何': 'Geometry/三维计算几何.md'
    - '数值积分': 
      - '辛普森积分': 'Geometry/辛普森积分.md'
      - '自适应辛普森': 'Geometry/自适应辛普森.md'
    - '点定位': 'Geometry/点定位.md'
    - '最小圆覆盖': 'Geometry/最小圆覆盖.md'
    - 'Voronoi图': 'Geometry/Voronoi图.md'
  - '其他': 
    - 'Others/index.md'
    - '离散': 'Others/离散.md'
    - '前缀和/差分': 'Others/前缀和差分.md'
    - '逆序对': 'Others/逆序对.md'
    - '扫描线': 'Others/扫描线.md'
    - '双指针': 'Others/双指针.md'
    - '倍增': 'Others/倍增.md'
    - '三分': 'Others/三分.md'
    - '枚举子集超集': 'Others/枚举子集超集.md'
    - '搜索': 
      - '剪枝': 'Others/剪枝.md'
      - '折半搜索': 'Others/折半搜索.md'
      - 'DLX': 'Others/DLX.md'
    - '分治':
      - '树上分治': 
        - '点分治': 'Others/点分治.md'
        - '边分治': 'Others/边分治.md'
        - '动态点分治': 'Others/动态点分治.md'
      - 'CDP分治': 'Others/CDP分治.md'
    - '随机':
      - '爬山': 'Others/爬山.md'
      - '模拟退火': 'Others/模拟退火.md'
    - '对拍': 'Others/对拍.md'
    - '常数优化': 'Others/常数优化.md'
    - '读入优化': 'Others/读入优化.md'

# Theme information
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: 更换到夜间模式
    - scheme: slate 
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: 更换到日间模式
  highlightjs: true
  language: 'zh'
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - fenced_code
  - meta
  - def_list
  - extra
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - tables

# Extra
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - Extra/JS/mathjaxhelper.js
